method: grid
metric:
  goal: maximize
  name: Val acc
parameters:
  cosine:
    values:
      - 1
  critic_epochs:
    values:
    - 2
  data_label_correlation:
    values:
      - 0.9
      - 0.7
  epochs:
    values:
      - 30
  in_dataset:
    values:
      - waterbird
  joint_indep:
    values:
      - 0
      - 1
  lr:
    values:
      - 0.0001
  manualSeed:
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
  momentum:
    values:
      - 0.9
  optimizer:
    values:
      - adam
  project_name:
    values:
      - wb_nurd
  reweight:
    values:
      - 1
  reweight_epochs:
    values:
    - 30
  weight_decay:
    values:
      - 0.005
program: main.py
project: nurd-ood-wb_nurd